#!/bin/python3

import subprocess

from inginious import input

import ingitest

# NOTE: exploitable


class Test(ingitest.TestCase):

    def __run(self, file: str) -> str:
        """Run the file and collect the outputs"""
        with subprocess.Popen(
            ["python3", file],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ) as pipe:
            stdout, _ = map(
                lambda b: b.decode(),
                pipe.communicate(),
            )
            rcode = pipe.returncode

        # Check exit code
        if rcode != 0:
            self.fail(
                "Votre code n'a pas pu être exécuté. "
                "Vérifiez que tous vos blocs sont correctement connectés."
            )
        return stdout

    def setUpClass(self):
        input.parse_template("student.pytpl")

    def test1(self):
        output = self.__run("student.pytpl").strip()

        self.assertEqual(
            output,
            "L'ADN du poil correspond à celui du directeur, c'est lui le coupable !",
            f"Réponse incorrecte, vous avez écrit : {output}",
            "Félicitations ! Vous avez réussi à trouver le coupable ! Le directeur s'effondre devant les preuves accablantes que vous venez de fournir, la police vous remercie pour votre aide"
        )


if __name__ == '__main__':
    Test().run().setFeedback()
