#!/bin/python3

import subprocess

from inginious import input

import ingitest

# Exercice:
# setvar NAME, AGE
# print(NAME)
# print(AGE)
# setvar NAME, AGE
# print(NAME)
# print(AGE)


class Test(ingitest.TestCase):

    def __run(self, file: str) -> str:
        """Run the file and collect the outputs"""
        with subprocess.Popen(
            ["python3", file],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ) as pipe:
            stdout, _ = map(
                lambda b: b.decode(),
                pipe.communicate(),
            )
            rcode = pipe.returncode

        # Check exit code
        if rcode != 0:
            self.fail(
                "Votre code n'a pas pu être exécuté. "
                "Vérifiez que tous vos blocs sont correctement connectés."
            )
        return stdout

    def setUpClass(self):
        input.parse_template("first.pytpl")

    def test1(self):
        try:
            name1, age1, name2, age2 = self.__run("first.pytpl").splitlines()
        except ValueError:
            self.fail("Oups! Vous n'avez pas écris deux noms et deux ages")
        else:
            try:
                age1, age2 = int(age1), int(age2)
            except ValueError:
                self.fail("Oups! Un age est une nombre, non?")
            else:
                for ndx, name in enumerate((name1, name2)):
                    self.assertNotEqual(
                        name.strip(),
                        "",
                        "Oups! Vous n'avez pas entré de nom!",
                        f"Oui! Le prénom numéro {ndx} est {name}"
                    )

                for adx, age in enumerate((age1, age2)):
                    self.assertNotEqual(
                        age,
                        0,
                        f"Oh! Vous êtes très jeune avec {age} ans.",
                        f"Félicitations! L'age numéro {adx} est {age}."
                    )


if __name__ == '__main__':
    Test().run().setFeedback()
