#!/bin/python3

import subprocess

from inginious import input

import ingitest

# Exercice: print("TEXT"["TEXT".index("WORD"):"TEXT".index("WORD")])


class Test(ingitest.TestCase):

    def __run(self, file: str) -> str:
        """Run the file and collect the outputs"""
        with subprocess.Popen(
            ["python3", file],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ) as pipe:
            stdout, _ = map(
                lambda b: b.decode(),
                pipe.communicate(),
            )
            rcode = pipe.returncode

        # Check exit code
        if rcode != 0:
            self.fail(
                "Votre code n'a pas pu être exécuté. "
                "Vérifiez que tous vos blocs sont correctement connectés."
            )
        return stdout

    def setUpClass(self):
        input.parse_template("substring-extract.pytpl")

    def test1(self):
        output = self.__run("substring-extract.tpl").strip()

        self.assertEqual(
            output,
            "effrayant, il était tout seul, oui, ou peut-être deux ? Il faisait noir, vous savez, ah, c'était tellement e",
            f"Attention, est-ce que vous avez uniquement affiché la sous-chaîne trouvée ? Vous avez écrit : {output}"
            f"Oui! Vous avez écris {output}."
        )


if __name__ == '__main__':
    Test().run().setFeedback()
