#!/bin/python3
import subprocess

from inginious import input

import ingitest

# Exercice: print("TEXT".upper())


class Test(ingitest.TestCase):

    def __run(self, file: str) -> str:
        """Run the file and collect the outputs"""
        with subprocess.Popen(
            ["python3", file],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ) as pipe:
            stdout, _ = map(
                lambda b: b.decode(),
                pipe.communicate(),
            )
            rcode = pipe.returncode

        # Check exit code
        if rcode != 0:
            self.fail(
                "Votre code n'a pas pu être exécuté. "
                "Vérifiez que tous vos blocs sont correctement connectés."
            )
        return stdout

    def setUpClass(self):
        input.parse_template("split-button.pytpl")

    def test1(self):
        output = self.__run("split-button.pytpl")
        self.assertEqual(
            output.strip(),
            "BONJOUR TOM, COMMENT ALLEZ-VOUS ?",
            "Attention aux énoncés, quel est l'objectif de la tâche 4 ? "
            f"Vous avez écrit : {output.strip()}",
            f"Correct ! Vous avez écrit : {output.strip()}"
        )


if __name__ == '__main__':
    Test().run().setFeedback()
