#!/bin/python3
#Open source licence goes here

import os
import subprocess
import shlex
from inginious import feedback
from inginious import input


if __name__ == "__main__":
    input.parse_template("student.py") #Replace sum.py by your filename on this line and the next
    p = subprocess.Popen(shlex.split("python3 student.py"), stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
    make_output = p.communicate()[0].decode('utf-8')
    if p.returncode:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Votre code n'a pas pu être exécuté. Vérifiez que tous vos blocs sont correctement connectés.")
        exit(0)
    elif make_output == "L'ADN du poil correspond à celui du directeur, c'est lui le coupable !\n":
        feedback.set_global_result("success")
        feedback.set_global_feedback("Félicitations ! Vous avez réussi à trouver le coupable ! Le directeur s'effondre devant les preuves accablantes que vous venez de fournir, la police vous remercie pour votre aide ")
    else:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Réponse incorrecte, vous avez écrit : " + make_output)