#!/bin/python3

import subprocess

from inginious import input

import ingitest

# Exercice:
# setvar HAIR
# HAIR++
# print(HAIR)


class Test(ingitest.TestCase):

    def __run(self, file: str) -> str:
        """Run the file and collect the outputs"""
        with subprocess.Popen(
            ["python3", file],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ) as pipe:
            stdout, _ = map(
                lambda b: b.decode(),
                pipe.communicate(),
            )
            rcode = pipe.returncode

        # Check exit code
        if rcode != 0:
            self.fail(
                "Votre code n'a pas pu être exécuté. "
                "Vérifiez que tous vos blocs sont correctement connectés."
            )
        return stdout

    def setUpClass(self):
        input.parse_template("student.pytpl")

    def test1(self):
        output = self.__run("student.pytpl").strip()

        try:
            output_int = int(output)
        except ValueError:
            self.fail(
                f"Une longeure est un nombre, mais {output} n'en est pas un.")
        else:
            self.assertEqual(
                output_int,
                3,
                f"Vous n'avez pas donné la bonne solution, la valeur contenue dans la variable nombre_poils est : {output_int}"
                f"Oui! Le nombre de poils est {output_int}."
            )


if __name__ == '__main__':
    Test().run().setFeedback()
